version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: pacmint-server
    ports:
      - "5555:5555"
    restart: unless-stopped
    network_mode: host

  client:
    build:
      context: .
      dockerfile: game/Dockerfile
    container_name: pacmint-client
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}  #utiliser la variable hôte ou une valeur par défaut
      - SDL_AUDIODRIVER=alsa
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  #affichage X11
      - /dev/snd:/dev/snd  #pour l'audio
    devices:
      - /dev/snd:/dev/snd
    network_mode: host
    depends_on:
      - server
    command: >
      bash -c "sleep 10 && python game/pacmint.py"
    tty: true
    stdin_open: true