version : '3.9'
services :
  server :
    build : ./server
    container_name: server
    ports :
      - "5555:5555"

  client :
    build : ./game
    container_name : client
    depends_on :
      - server