name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Installer les dépendances pour chaque sous-projet
      - name: Install game requirements
        run: pip install -r game/requirements.txt

      - name: Install server requirements
        run: pip install -r server/requirements.txt

      - name: Install site_web requirements
        run: pip install -r site_web/requirements.txt